### PR TITLE
Updated with my ideas

### PR DESCRIPTION
**Pull request by urathoure**

### CODE REVIEW

**Comment by mistermantas** [comment]
Interesting, but are you sure this makes sense after my paragraph's last sentence?

> But less about my technique, dear reader, there's something I've been meaning to tell you...

**Comment by urathoure** [comment]
i would be creating another re with some relatable views

**Comment by mistermantas** [comment]
you can only make one PR, so make this one the best you can

**Review by urathoure — COMMENTED** [review]
Meaningful relationships are what matter most. Showing the people around you that you care about them and that you’re willing to put them first, is the mark of a true leader. Great leaders are vulnerable and unselfish. Ultimately, they thrive by exhibiting this behavior and in so doing, they earn the respect of all.

**Comment by mistermantas** [comment]
thank you for contributing!

**Pull request merged**
