### PR TITLE
adds my contribution to the readme

### PR DESCRIPTION
**Pull request by SincerelyBrittany**

### CODE REVIEW

**Comment by mistermantas** [comment]
Nice! Uh, but based on the contributing rules, you can't edit what's behind you -- just keep writing forward.

You can merge the two paragraphs into one. It still makes sense, I think.

**Comment by mistermantas** [comment]
I assume the closing was accidental.

**Comment by SincerelyBrittany** [comment]
Yes, I am still learning. I am going to resubmit now.

**Comment by mistermantas** [comment]
You don't have to, I already added your changes! :)

**Comment by SincerelyBrittany** [comment]
Thank you and I apologize for the confusion.

**Pull request merged**
